### ISSUE TITLE
Disable for domain

### ISSUE THREAD

**Issue by facegit** [nuevvo/engintron#17]
Is it possible to disable Engintron for a certain domain?

**Comment by fevangelou** [comment]
Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.

In other words, you won't need to exclude domains :)

**Comment by aledel76** [comment]
Where can I exclude a domain in the Engintro's backend? Can someone send me a screenshot?
Thanks
