### ISSUE TITLE
Installed fine yet this is in error log.

### ISSUE THREAD

**Issue by highacid** [nuevvo/engintron#20]
2014/09/27 07:25:01 [error] 19505#0: *51 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 07:30:01 [error] 19505#0: *56 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 07:35:01 [error] 19505#0: *63 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 07:40:01 [error] 19505#0: *75 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 07:45:01 [error] 19505#0: *82 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 07:50:01 [error] 19505#0: *97 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 07:55:02 [error] 19505#0: *115 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:00:01 [error] 19505#0: *152 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:05:01 [error] 19505#0: *162 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:09:57 [error] 19505#0: *178 open() "/usr/share/nginx/html/manager/html" failed (2: No such file or directory), client: 74.208.173.136, server: localhost, request: "GET /manager/html HTTP/1.1", host: "80.85.86.97:80"
2014/09/27 08:10:01 [error] 19505#0: *179 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:10:06 [error] 19505#0: *180 open() "/usr/share/nginx/html/manager/html" failed (2: No such file or directory), client: 74.208.173.136, server: localhost, request: "GET /manager/html HTTP/1.1", host: "80.85.86.104:80"
2014/09/27 08:15:01 [error] 19505#0: *193 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:20:01 [error] 19505#0: *197 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:22:46 [error] 19507#0: *203 open() "/usr/share/nginx/html/fafa/faf/fa.php" failed (2: No such file or directory), client: 140.130.142.18, server: localhost, request: "GET /fafa/faf/fa.php HTTP/1.1", host: "80.85.86.97"
2014/09/27 08:22:47 [error] 19507#0: *204 open() "/usr/share/nginx/html/phpMyAdmin/scripts/setup.php" failed (2: No such file or directory), client: 140.130.142.18, server: localhost, request: "GET /phpMyAdmin/scripts/setup.php HTTP/1.1", host: "80.85.86.97"
2014/09/27 08:22:48 [error] 19507#0: *205 open() "/usr/share/nginx/html/pma/scripts/setup.php" failed (2: No such file or directory), client: 140.130.142.18, server: localhost, request: "GET /pma/scripts/setup.php HTTP/1.1", host: "80.85.86.97"
2014/09/27 08:22:49 [error] 19507#0: *206 open() "/usr/share/nginx/html/myadmin/scripts/setup.php" failed (2: No such file or directory), client: 140.130.142.18, server: localhost, request: "GET /myadmin/scripts/setup.php HTTP/1.1", host: "80.85.86.97"
2014/09/27 08:25:01 [error] 19507#0: *209 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:30:01 [error] 19507#0: *215 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:35:01 [error] 19507#0: *222 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:40:01 [error] 19507#0: *230 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:45:01 [error] 19507#0: *296 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 08:50:01 [error] 19507#0: *306 open() "/usr/share/nginx/html/whm-server-status" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /whm-server-status HTTP/1.0"
2014/09/27 09:20:18 [error] 24787#0: *64 open() "/usr/share/nginx/html/robots.txt" failed (2: No such file or directory), client: 192.99.39.79, server: localhost, request: "GET /robots.txt HTTP/1.1", host: "www.uhl-services.info"

**Comment by fevangelou** [comment]
Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.

Should also resolve your issue with WHM's status page.

**Comment by virtuali1151** [comment]
Still have that issue as well, even with the new 1.5.2 version...
