### ISSUE TITLE
[Question] Exclude vhost from nginx

### ISSUE THREAD

**Issue by RaNd250** [nuevvo/engintron#21]
Hi, i'm about to test your app, after testing "others" methods of install nginx in cPanel.
Is there a way to exclude a site/vhost from nginx ?

In previous installs with nginx some Joomla sites had issues behind nginx ( from apache were served just fine)

**Comment by fevangelou** [comment]
Things have changed with 1.5.0 though :)

Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.
