### ISSUE TITLE
Some updates for the future

### ISSUE THREAD

**Issue by AgentGod** [nuevvo/engintron#24]
I'm not sure is it the right place for some feature requests. This is my firs post in GitHub.
I have tried the plugin and it is almost excellent and the features which will be good to see in the future is:
1. Page-mod speed included or option to choose on installation, I installed it as Apache module at the moment but it doesn't work, maybe because static files are handled by  nginx.
2. Each cache to be in it's own virtual host folder. I want to use it on WordPress sites and I don't like cache plugins, so it will be excellent if each cache is in it's own folder and with simple plugin from WP to be able to purge the cash. 
Also I found a tutorial on http://www.djm.org.uk/wordpress-nginx-reverse-proxy-caching-setup/ which can help for better optimization for WordPress or even Joomla like sites.

**Comment by fevangelou** [comment]
Engintron 1.5.0 is here. Complete re-write.

There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content. Performance is measured between hundreds to thousands %. We're talking about improving concurrent page serving from a few hundreds to 20,000 or more.
