### ISSUE TITLE
Installation error - www.stderr.net (domain down) 

### ISSUE THREAD

**Issue by ninostar** [nuevvo/engintron#26]
Hi,

Installation can't be finished, as domain www.stderr.net is down. Can you change download location of needed packets to somewhere else? 

Kind regards

**Comment by fevangelou** [comment]
Resellers rejoice.

Engintron 1.5.0 is here. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.

In other words, it's a "set and forget" solution to optimize your cPanel server.
