### ISSUE TITLE
Default port not set back after uninstall

### ISSUE THREAD

**Issue by Bananenbaas** [nuevvo/engintron#32]
Hi guys, 

First of all great job on this plugin! I really liked it! I had to uninstall it for some work on my server, when I uninstalled your plugin I noticed my http connections were failing, I got a "this webpage is not available" notice. First I was like WTF, because the HTTPS connections where doing fine!
When I took a closer look into my httpd.conf file, I noticed al the http ports (normally port 80) were still on port 8081... I replaced all the 8081 to 80 and then everything worked fine again! 

Just to let you know! 

Yours,

Bananenbaas

**Comment by Friendbg** [comment]
Hi, just wanted to confirm this issue. Today I uninstall and install again engintron and saw that when I uninstall it apache port was not changed to default.

Thanks

**Comment by AgentGod** [comment]
Hi, 
I had the same problem, but it's can be fixed easily through Home » Server Configuration » Tweak Settings -- Apache non-SSL IP/port -- just select the 0.0.0.0:80

Regards

**Comment by Nirjonadda** [comment]
Its best to do, Developer can add Support for restore original port if uninstalled Nginx plugin.

**Comment by fevangelou** [comment]
It's been fixed already.

Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.
