### ISSUE TITLE
Installed on CentOS 6.6 server running PHP5.5 & Apache 2.4 (PHP Handler was FCGI) with terrible results

### ISSUE THREAD

**Issue by brianjking** [nuevvo/engintron#34]
I installed this on my CentOS 6.6 64bit dedicated SSD server that was using PHP 5.5 and Apache 2.4 and went from receiving Google Pagespeed scores in the 80's to barely scraping 40 for desktop and even lower for mobile.

Compression wasn't showing as enabled, etc. 

Any idea what's up? Please help!

Thanks!

**Comment by fevangelou** [comment]
Gzip compression is enabled by default on Nginx after you install Engintron. In order for me to see what's possibly wrong, you need to send me screenshots of Pagespeed's evaluation before and after installing Engintron.

**Comment by fevangelou** [comment]
Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.
