### ISSUE TITLE
Any opportunity for using PHP-FPM?

### ISSUE THREAD

**Issue by brianjking** [nuevvo/engintron#36]
Is there a way to use PHP-FPM along with Engintron?

**Comment by fevangelou** [comment]
That would mess up with cPanel's PHP unfortunately...

**Comment by brianjking** [comment]
@fevangelou Yeah, I closed this since I saw it was still open. I found a better solution a long time ago, especially since no one responded here in over a year. https://github.com/AnoopAlias/nDeploy https://support.sysally.net/projects/ndeploy/wiki
