### ISSUE TITLE
"Sync Nginx with Apache vhosts" not working

### ISSUE THREAD

**Issue by gbassoc** [nuevvo/engintron#39]
I changed the IP of a domain, then ran "Sync Nginx with Apache vhosts" and restarted NginX and Apache but my domain page is showing "Welcome to nginx" so it appears that synching is not working, what is the manual steps I need to take to get my websites back

**Comment by fevangelou** [comment]
Try clearing Nginx's cache. Redo the sync. If that doesn't work, reboot the server. If that still doesn't work, simply uninstall Engintron.

What cPanel version are you on?

**Comment by gbassoc** [comment]
several times I have redone the synch and I have forces cleared the cache,
when I tried to uninstall nginx it left the web server in a worst state
(see my comment on issue # 38)

cpanel 11.48.0 (build 11)

**Comment by fevangelou** [comment]
The only change it performs in cPanel is the port change for Apache. Maybe they changed their API in recent versions and the script cannot revert the port changes. It does not leave your server in a "worse state". So in this case, simply change Apache port to 80 and 443 (for SSL) in Tweak Settings (WHM), "save" and then simply restart Apache.

**Comment by fevangelou** [comment]
Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.
