### ISSUE TITLE
subdomains/parked domains (not using public_html) root folder and vhosts

### ISSUE THREAD

**Issue by niladam** [nuevvo/engintron#41]
I just found this and i have a few questions after reading the install script.

According to the install script, if i have a subdomain that uses a different root folder (ex: /home/user/sites/subdomain.domain.org) that subdomain won't actually work, as your script does a for and gets the DNS for the user that are located in /var/cpanel/users.

I think the script should actually do a search in the userdata, and get the documentroot.

I think this could actually work, by doing something like:

```shell
cd /var/cpanel/users
for USER in *; do
	for DOMAIN in `cat $USER | grep ^DNS | cut -d= -f2`; do
		IP=`cat $USER|grep ^IP|cut -d= -f2`;
		ROOT=`grep ^$USER: /etc/passwd|cut -d: -f6`;
		DOMROOT=`cat /var/cpanel/userdata/$USER/$DOMAIN | grep documentroot | cut -d: -f2 | sed -e "s/ //g"`;
done
done
```

And now **$DOMROOT** actually contains the document root. However, since for example **PARKED** domains are placed on TOP of main domain of the account, this should also actually rely on the **FIRST** *DNS=* line (not DNS=1, DNS=2..etc -- ie: mycooldomain.org) to actually detect the PARKED domain (ie: anothercool.org) which should probably be set as **parked-domain** (without .com, .net, .org..etc) .MAIN-DNS (ie: anothercool.mycooldomain.org).

**Comment by niladam** [comment]
@fevangelou ?:)

**Comment by fevangelou** [comment]
Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.
