### ISSUE TITLE
Websites stopped working

### ISSUE THREAD

**Issue by acidgod** [nuevvo/engintron#42]
Installed it on my cpanel, the vhosts got rebuild, websites stopped working. After uninstall had to rebuild my server to get the websites back

**Comment by Nirjonadda** [comment]
I think the Developer no more Support for this Plugins because no update coming.

**Comment by katmai** [comment]
Yeah i believe this project is kinda dead.

**Comment by Friendbg** [comment]
Hi, add this at 935 line on engintron.sh : 

	sed -i 's/:8081/:80/g' /etc/httpd/conf/httpd.conf

and your websites will be live again after uninstalling engintron.

I also think that development is dead on this project :(

**Comment by fevangelou** [comment]
The uninstaller has been fixed.

I would also suggest you update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.
