### ISSUE TITLE
Sync Ngninx with apache hosts will remove already modified .conf files 

### ISSUE THREAD

**Issue by sugarzlol** [nuevvo/engintron#43]
Hello,
First of all thank you so much for this great tool, it did a tremendous impact on my sites.
However I was writing a custom cookie code for one domain, but I was surprised it get deleted whenever I sync with apache.

I rarely add new domains but I just forget sometimes that it delete modified configurations when I sync.
Also I think a simpler solution is to add it to proxy.conf but I think the check is not needed for the other domains.
Is it possible to sync only new domains when doing the check? 

Thank you

**Comment by fevangelou** [comment]
The sync option is meant not just for new domains but for "patching" old ones with new rules.

What I could do is have a generic include file for each cPanel domain or account which would make additional rules permanent.

What do you usually add in your custom rules?

**Comment by fevangelou** [comment]
Please update to Engintron 1.5.0. There is no vhost sync anymore and both proxying & caching is much more optimized and now available to any type of website, even those with user generated content.
