### ISSUE TITLE
Expires 1d to longer?

### ISSUE THREAD

**Issue by mo-unifyservices** [nuevvo/engintron#45]
Hey There,

Love Engintron! Absolutely the best way to install NGINX on cPanel.

One question, is there a way to set the default Expires for CSS/JS/HTML files to longer than 1d?

Generally found in the /etc/nginx/<website>.conf:

`location ~* \.(htm|html|css|js)(\?[0-9a-zA-Z]+)?$ {`
`	expires				1d`
`....`

Is there a way to default the Expires?
Thanks and great work!

**Comment by fevangelou** [comment]
Sure. Modify the main install file as seen here https://github.com/nuevvo/engintron/blob/master/engintron.sh and more specifically, change 7d or 1d in lines 369, 377 and 385 to whatever you want. Then resync Nginx/Apache via WHM for the changes to take effect.

**Comment by mo-unifyservices** [comment]
Awesome! Thanks!
