### ISSUE TITLE
Wildcard hosts don't work

### ISSUE THREAD

**Issue by chrispage1** [nuevvo/engintron#46]
Hi,

Wildcard Apache hosts fail -

`root@server [/etc/nginx/conf.d]# service nginx restart
nginx: [emerg] invalid server name or wildcard "www.*.example" on XXX.XXX.XXX.XX:80
nginx: configuration file /etc/nginx/nginx.conf test failed`

Hope you can help with this!

**Comment by fevangelou** [comment]
Read this: http://nginx.org/en/docs/http/server_names.html

The asterisk should either be first or last in the hostname definition. What works for Apache doesn't necessarily mean it works for Nginx too.

Additionally, IMHO you should avoid using wildcards in hostnames, unless there's a very very important reason to do so.
