### ISSUE TITLE
is APC required? 

### ISSUE THREAD

**Issue by kristopherlarson** [nuevvo/engintron#48]
Is APC required to make this work? From the research I've done, this module is hardly updated or even supported. It seems everyone is moving towards zend opcache and thats what I have enabled on my server.

**Comment by fevangelou** [comment]
Actually, it's now called APCu and it's very active in development.

https://pecl.php.net/package/APCu

Check the release dates.

APCu is different from Opcache and it does speed up things a lot for CMSs like Joomla, WordPress etc. which offer (either natively or by extensions) the option to cache the entire output of their content in APCu's cache. The benefits are obvious: less disk i/o and faster cache access as everything is stored in memory.

To install the latest compatible build of APCu with cPanel's PHP 5.x packages (which is APCu 4.x), execute these commands as root user via SSH:

$ yum install pcre-devel make
$ pecl install channel://pecl.php.net/APCu-4.0.10

The first line will make sure you have some basic requirements (newest cPanel builds have those) and the 2nd line directly installs version 4.0.10 on your system. Just visit PHP's configuration (advanced tab) afterwards and make sure apcu.so is listed in the included modules. If you rebuild Apache, you need to repeat the installation step (the 2nd line).

You will also need to edit your php.ini file and add these 2 lines to enable APCu:

apc.enabled = 1
apc.shm_size = 256M

In cPanel, php.ini is located in: /usr/local/lib/php.ini

Don't try using cPanel's PECL modules installer. It's broken for years and cPanel doesn't care to fix it or at least they won't fix it for FastCGI PHP builds in EasyApache.

Finally, if you have CMSs with APC/APCu caching drivers, just make sure you select APC or APCu to enable caching. Joomla has this natively (it's under Global Configuration but APCu has to be installed first) and WordPress can enable APCu caching when used with https://wordpress.org/plugins/apcu/ - additionally plugins like WP Super Cache or W3 Total Cache will even store their page cache output in APCu.

An up to date guide is published here: http://www.joomlaworks.net/blog/item/153-install-apc-apcu-on-a-whm-cpanel-server

**Comment by masteranalyze** [comment]
What does apcu and zend opcache does not do?

They can be used both or they are conflicts ?Witch one is more better with nginx?If anyone run some tests?!About this.

**Comment by fevangelou** [comment]
You can use both. If you have PHP 5.4+ use the new APCu. For 5.3 or lower
use APC. Opcache will only work with php 5.5+ and it has no conflicts with
APCu. In fact it's recommended to have both installed.

**Comment by masteranalyze** [comment]
I use php 5.6,and looking forward to use php 7,when cpanel will have it on easy apache 4-multi php.

I will use both,thank you.

Any ideea or maybe an inclusion into engintron of some kind of gui for opcache and apcu ?

Something like this : https://github.com/PeeHaa/OpCacheGUI ,for apcu does something similar?

Maybe they can be somehow integrated in Engintron,if they already exist,what do you think?!

**Comment by fevangelou** [comment]
Yeap, that's nice to have. Noting down to integrate them in upcoming versions. Both APCu and Opcache have "official" GUIs :)

**Comment by masteranalyze** [comment]
Okay,i was suggesting ,if those guis can be present in engintron2 ? To have it ,all in one place to manage it from cpanel/whm basically.

**Comment by fevangelou** [comment]
I'll get them in much earlier :) I believe I can further enrich Engintron with various missing utilties from cPanel, so I'll have to redesign the v2 concept.

**Comment by masteranalyze** [comment]
That will be great,and indeed alot of utilities is missing from cpanel .

One thing that is missing,is also to be able to setup that INODES ,cpu usage limit,there is no plugin into the market,for that,there is lv from cloudlinux,but i preffere Centos 6.7 .

Cloudlinux haves alot of problems too,and it does gets into conflict with cpanel/whm ,at least when you use easyapache 4,is not compatible at all.

**Comment by fevangelou** [comment]
That's really hard to resolve without some sort of containerization or virtualization. If you're interested in something like that for commercial purposes (=your clients), email me at engintron [at] nuevvo [dot] com for more.

**Comment by masteranalyze** [comment]
Look here : http://docs.cloudlinux.com/index.html?understanding_lve.html 

I know the guys from BetterLinux,that did shutdown last year,also did build it up,so i think is possible.

And yes,i will to pay for that kind of plugin,that can do basic the same thing as LVE manager from cloudlinux.
