### ISSUE TITLE
easyapache 4

### ISSUE THREAD

**Issue by masteranalyze** [nuevvo/engintron#50]
Any ideea when engintron 2.0 will be available?And if this version will work on easyapache 4?

Right now,this 1.5 version only work on easyapache  3?!

**Comment by highacid** [comment]
I go with this, please add support for EasyApache 4, latest cpanel already has got on it, and alto in beta still works great!

**Comment by fevangelou** [comment]
EasyApache4 blocks the installation of Nginx from the official Nginx repos.
Maybe raise this to cPanel so they tell us why the hell they're doing this?

**Comment by fevangelou** [comment]
You can contribute to this post if you want with the error messages you got:

https://forums.cpanel.net/threads/why-does-easyapache4-block-nginx-installation-using-yum-official-nginx-repos.524241/

**Comment by masteranalyze** [comment]
it`s absolute absurdly,why the heck to block ?

I mean for easy apache 3 does work right ?

And for easy apache is blocked?!

Makes no sense...i will check the post as well....this certainly must be something wrong from their side.

**Comment by fevangelou** [comment]
They stated it's a bug and they will resolve it. So that's a good thing to know. Closing the issue for now as I have updated the project's readme page.
