### ISSUE TITLE
Roadmap engintron or milestones

### ISSUE THREAD

**Issue by masteranalyze** [nuevvo/engintron#52]
Maybe we can build an road map,or some milestones here for this project.

What do you say ?

To have for 1.6 implementation gui for opcache ,1.7 implementation gui APCU ,etc 

Just an example.

In order to put things in order,and have an progress.
p.s:You should call it ENGINETRON ,if possible,engintron seems like an E missing!EngineTron sounds more better,just my opinion.

**Comment by fevangelou** [comment]
I originally had "e" in the middle but beta testers actually pronounced in
and it was weird. So I ditched it.

As for the roadmap, I'll post a new page in the wiki with my notes, your
suggestions for APC/opcache GUIs and anything else that users suggest.

**Comment by masteranalyze** [comment]
hey fev,
okay great,do that...and note this as well :+1: 
The Nginx definition does not currently support IPv6 if that's what you're asking. But that's easy to fix (I'll set it for 1.5.1). -this also

And this is good ideea too : One of things I wish to integrate in Engintron soon is the automated generation of SSL certificates using Let's Encrypt which is 100% free.

We should note them,to keep track on them and implement them.

**Comment by fevangelou** [comment]
Roadmap is up already in the wiki: https://github.com/nuevvo/engintron/wiki/Engintron-Roadmap

Closing issue.

**Comment by masteranalyze** [comment]
good work fev!
