### ISSUE TITLE
XMLRPC attack Mitigation

### ISSUE THREAD

**Issue by ImLuke954** [nuevvo/engintron#53]
In the previous version of engintron, I used to mitigate xmlrpc attack by placing the below line within the _server {}_ configuration block in vhosts file of the target domain

`if ($http_user_agent ~ WordPress) { return 444; }`

Now as the individual vhosts are removed in the latest version of engintron, where do I need to place that code to prevent XMLRPC attack?

**Comment by fevangelou** [comment]
In default.conf, right after the server_name line would be sufficient to
place any such exclusions and the good thing is they'll now work globally.
