### ISSUE TITLE
DNS points to prohibited IP

### ISSUE THREAD

**Issue by jazz1611** [nuevvo/engintron#54]
All domains running via CloudFlare have error 
Error 1000 Ray ID: xxxxxxxxx • 2016-02-03 18:39:53 UTC
DNS points to prohibited IP

I was installed to CentOS 7. If i comment "resolver 8.8.8.8 8.8.4.4;" on nginx.conf, it will show 502 bad gateway. Also i was uncomment 3 lines related CloudFlare.

How to resolve it?

Regards,

**Comment by fevangelou** [comment]
Are you located in China? If so, the Google DNS resolvers may be blocked.

In this case, simply change the 2 IPs with those from OpenDNS:
208.67.222.222 208.67.220.220

If that's not the case, paste back the contents of the files you've changed.

**Comment by fevangelou** [comment]
Please note that if you use Cloudflare you should also set your server's
shared IP address inside proxy_params_common.

There are comments to help you there but I'll make sure to make a page in
the Wiki for CloudFlare alone.

**Comment by masteranalyze** [comment]
If you have nginx i don`t think the free plan from cloudflare would help you,except the fact they leverage the thing across the server,and maybe it will load an little bit more fast,but maybe fev can tell us more about this as i did not tested it.

Also cloudflare only cache static things,so if you have dynamic website,like an forum or something like an social network,or blogs with comments and so on,and your using the free plan from cloudflare,i don`t think it will make things load faster or better.

It`s always good to keep it as simple as possible,and check if they are trully benefits for your case.

**Comment by mrqaidi** [comment]
i have this issue  and dont know  how to put shared IP address inside proxy_params_common.
there is no doc about  set shared address

**Comment by fevangelou** [comment]
@mrqaidi See here: https://github.com/engintron/engintron/wiki/Engintron-&-the-%22Custom-Rules%22-file-(for-Nginx)
