### ISSUE TITLE
sh: /etc/init.d/nginx: No such file or directory

### ISSUE THREAD

**Issue by junglon** [nuevvo/engintron#55]
When I click the "Check configuration for errors" an error shown 

> Checking Nginx configuration...
> sh: /etc/init.d/nginx: No such file or directory
> 
Is this normal or not?
Server : Centos 7.2, cPanel

**Comment by tess0072** [comment]
I am experiencing the same issue. Nuevvo did mention that there is a known issue with Centos 7 so perhaps we just need to wait for a fix? I can't get this to work at all on my Centos/Cloudlinux 7 box at all.

**Comment by fevangelou** [comment]
Please allow for a few days to verify CentOS 7 compatibility.
