### ISSUE TITLE
Favicon icon are not showing

### ISSUE THREAD

**Issue by Nirjonadda** [nuevvo/engintron#57]
Hello,

I have an issue after Installing Engintron v1.5.0, website Favicon icon are not showing. Please let me know to fixing on this issue.

*** System Info ***
OS: CentOS release 6.7 (Final)
WHM 54.0 (build 8) with EasyApache 3

Thanks

**Comment by Nirjonadda** [comment]
/favicon.ico

404 Not Found
nginx

**Comment by fevangelou** [comment]
There is no issue really. Just be sure, clean the Nginx cache/temp files
via Engintron in WHM and the open a private window in your browser and
check your site.

**Comment by fevangelou** [comment]
Does the file actually exist if you call the URL from port 8080?

**Comment by Nirjonadda** [comment]
Already doing Nginx cache/temp files via Engintron in WHM and the open a private window in web browser but issue are still on my site. This issue only happen with Engintron. /favicon.ico files have on my server. I am using vBulletin 4.x.x with Apache 2.4.18 and PHP 5.6.17 but I have one plugin [DBTech] DragonByte SEO (http://www.vbulletin.org/forum/showthread.php?t=308615) that Requirements edit Nginx Configuration if using Nginx but before I am used Apache booster and Nginx Admin without any Issue. Please can you let me know Where i put nginx.conf code with DBSEO nginx.conf ?

DBSEO nginx.conf IS:

location ~* \.(png|jpg|jpeg|gif|ico)$ 
	{
		expires 30d;
		log_not_found off;
	}
	location /
	{
		try_files $uri $uri/ /dbseo.php;
	}

	location ~ ^((?!dbseo).)*\.php$
	{
		rewrite ^/(.*)$ /dbseo.php last;
	}
	
	location ~* \.(php)$
	{
		fastcgi_index index.php;
		fastcgi_pass unix:/var/run/php5-fpm.sock;
		include /etc/nginx/fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
		fastcgi_param PATH_TRANSLATED $document_root$fastcgi_script_name;
	}

**Comment by fevangelou** [comment]
Engintron requires no additional configuration changes!

Send me over your site's URL to have a look. I'm sure it's something
trivial and easy to resolve.

**Comment by Nirjonadda** [comment]
My Site Is: http://www.nirmoladda.com

**Comment by Nirjonadda** [comment]
Favicon URL: http://www.nirmoladda.com/favicon.ico

**Comment by fevangelou** [comment]
Can you please make sure port 8080 is open in your firewall?

**Comment by Nirjonadda** [comment]
Yes, port 8080 is open in Server firewall but issue are still same.

**Comment by Nirjonadda** [comment]
Please can you let me know, How to turn OFF engintron without Remove?

**Comment by fevangelou** [comment]
The problem with the favicon.ico is minimal really. I'm assuming it's probably a "owner" permissions issue. Can you make sure that file has the correct owner and 0644 permissions?

Also, if you grab v1.5.1 just released, you can issue:

$ bash /engintron.sh disable
...to disable Nginx and switch back to Apache and

$ bash /engintron.sh enable
...to re-enable Nginx and switch Apache to port 8080.

**Comment by Nirjonadda** [comment]
Yes that file has the correct owner and 0644 permissions but cannot update 1.5.1

root@oa [/etc/nginx]# cat proxy_params_common.bak
cat: proxy_params_common.bak: No such file or directory
root@oa [/etc/nginx]# cat proxy_params_dynamic.bak
cat: proxy_params_dynamic.bak: No such file or directory
root@oa [/etc/nginx]# cat proxy_params_static.bak
cat: proxy_params_static.bak: No such file or directory
root@oa [/etc/nginx]# cat conf.d/default.conf.bak

**Comment by Nirjonadda** [comment]
Please can you let me know how to update 1.5.1?

**Comment by Nirjonadda** [comment]
Done, update 1.5.1 same process to installation?

**Comment by Nirjonadda** [comment]
Favicon icon are working after Engintron disabled. So this issue with Engintron.

**Comment by fevangelou** [comment]
Try something please. Add a comment # in front of line 69 in "default.conf"...

Change this:
location = /favicon.ico { log_not_found off; access_log off; }

To this
#location = /favicon.ico { log_not_found off; access_log off; }

Enable Engintron and check once more.

BTW, if you update just now, you'll see that the are control to toggle enable/disable from with WHM's app dashboard for Engintron (to make the whole process instant and easier when you don't have access to a terminal).

**Comment by fevangelou** [comment]
I believe that this specific rule may overwrite the caching directives, that's why Nginx can't fetch it. And it only happens when favicon.ico is at the root of a site...

**Comment by fevangelou** [comment]
Yeap, that's it... I'm updating the Nginx definition file and re-uploading.

**Comment by Nirjonadda** [comment]
"default.conf" are changed but issue are still same, OK please let me know when you are re-uploading completed

**Comment by fevangelou** [comment]
No, it works. You just need to clean the Nginx cache/temp files afterwards.

If you grab the update I pushed just now and re-install, you'll see it's fixed.

Example: http://www.fightsaga.com/favicon.ico (Nginx) & http://www.fightsaga.com:8080/favicon.ico (Apache)

:)

Thanks for making me see this error, as the effect would have been worse with robots.txt being completely blocked.

**Comment by Nirjonadda** [comment]
Also Apache Status are not working: http://postimg.org/image/8pl80tcw1/full/

**Comment by Nirjonadda** [comment]
OK I will going to update and let you know.

**Comment by Nirjonadda** [comment]
Yes Favicon icon are working now. Enable/Disable Engintron are getting error from WHM's app dashboard.

**************************************
*         Enabling Engintron         *
**************************************
Stopping nginx: [  OK  ]
=== Switch Apache to port 8080 ===


=== Distill changes in Apache's configuration and restart Apache ===
Distilled successfully
Built /usr/local/apache/conf/httpd.conf OK


Starting nginx: [FAILED]
Stopping nginx: [FAILED]
Starting nginx: [  OK  ]

**************************************
*         Engintron Enabled          *
**************************************

**Comment by fevangelou** [comment]
Grab the final update which includes the fix for nginx_status and also the metrics for that page are available in "Nginx Status" in the WHM app.

If for some reason the enable/disable function doesn't work in the WHM app, just run it once from the terminal:

$ /engintron.sh disable
$ /engintron.sh enable

And you should be fine.

Thanks again for your input.

**Comment by Nirjonadda** [comment]
Doing this final update but Also Apache Status are not working: http://postimg.org/image/8pl80tcw1/full/

Does Apache Status are fixed with this update?

**Comment by Nirjonadda** [comment]
I think all are working fine ! Its great to have integration with varnish.

Thanks for your great Support.

**Comment by fevangelou** [comment]
Apache status page is now fixed.
