### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by elaka** [nuevvo/engintron#58]
Hello,
These are the last messages:

Transaction Summary
================================================================================
Install       1 Package(s)

Total download size: 352 k
Installed size: 872 k
Downloading Packages:
nginx-1.8.1-1.el6.ngx.x86_64.rpm                         | 352 kB     00:00     
Running rpm_check_debug
Running Transaction Test

Transaction Check Error:
  file /etc/rc.d/init.d/nginx from install of nginx-1.8.1-1.el6.ngx.x86_64 conflicts with file from package cpnginx-1.9.4-3.x86_64

Error Summary
-------------

***************************************************

 IMPORTANT
 Nginx was not installed (perhaps due to conflicts)
 Exiting...

***************************************************
and when I run root@server1 [~]# service httpd start
I get:
[Sat Feb 06 01:59:10 2016] [warn] module rpaf_module is already loaded, skipping
Syntax error on line 3 of /usr/local/apache/conf/includes/rpaf.conf:
Invalid command 'RPAF_Enable', perhaps misspelled or defined by a module not included in the server configuration

**Comment by fevangelou** [comment]
Looks like you already had another cPanel plugin with Nginx already
installed. If that's the case, either uninstall that other plugin or simply
follow the process to uninstall Engintron to clean some of its entries in
Apache.

**Comment by elaka** [comment]
the prob occurs here:

Rebuilding configuration without any local modifications.

info [rebuildhttpdconf] Missing owner for domain virtio.localdomain, force lookup to root
Failed to generate a syntactically correct Apache configuration.
Bad configuration file located at /usr/local/apache/conf/httpd.conf.work.LCiVSqSfWI2hpiFb
Error:
Configuration problem detected on line 3 of file /usr/local/apache/conf/includes/rpaf.conf:	Invalid command 'RPAF_Enable', perhaps misspelled or defined by a module not included in the server configuration

	--- /usr/local/apache/conf/includes/rpaf.conf ---
	1# RPAF
	2LoadModule              rpaf_module modules/mod_rpaf.so
	3 ===> RPAF_Enable             On <===
	4RPAF_ProxyIPs           127.0.0.1 23.91.66.133 143.95.98.137 10.7.18.229 
	5RPAF_SetHostName        On
	6RPAF_SetHTTPS           On
	7RPAF_SetPort            On
	8RPAF_ForbidIfNotProxy   Off
	9RPAF_Header             X-Real-IP
	--- /usr/local/apache/conf/includes/rpaf.conf ---



[Sat Feb 06 05:00:53 2016] [warn] module rpaf_module is already loaded, skipping
Syntax error on line 3 of /usr/local/apache/conf/includes/rpaf.conf:
Invalid command 'RPAF_Enable', perhaps misspelled or defined by a module not included in the server configuration

**Comment by fevangelou** [comment]
Did you run the Engintron uninstaller?

**Comment by elaka** [comment]
yes I did

**Comment by fevangelou** [comment]
Then simply delete the file /usr/local/apache/conf/includes/rpaf.conf and restart Apache.

**Comment by elaka** [comment]
rpaf.conf deleted and Apache restarted but it's still rebooting itself :( I opened a support ticked with my host!

**Comment by fevangelou** [comment]
BTW, you never mentioned CentOS, cPanel & EasyApache versions...

And of course you didn't verify whether you already had another cPanel Nginx plugin (there's a cpnginx package mentioned above).

**Comment by elaka** [comment]
CENTOS 6.7 x86_64 kvm , cPanel 11.54.0.12 and EasyApache 3
and sorry no I did remove the other plugin (cpnginx) prior to installation !!

**Comment by fevangelou** [comment]
So it looks like the problem comes from cpnginx originally. It did not properly uninstall and this caused issues with Engintron. I'd recommend you look for any updates to cpnginx. Get them, install cpnginx again and uninstall once more. Then try re-installing Engintron. If the cpnginx uninstallation went through OK, the Engintron will have no issue getting installed as well.

Alternatively, you can send me temporary root access to have a look if you want at: engintron [at] nuevvo [dot] com

**Comment by elaka** [comment]
ok cool

**Comment by elaka** [comment]
tech support guy installed nginx with  lynx -source http://129.121.132.46/downloads/nginx_cpanel | sh 
nginx/1.9.4
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
and server is now working,
I'm worried to install your plugin which uses nginx/1.8!!

**Comment by fevangelou** [comment]
He installed cpnginx which in turn installs Nginx from source (actually it looks like a custom yum binary called cpnginx) and not directly using the official Nginx repositories. Using the Nginx repositories you usually get absolute stable releases and unlike cpnginx, whenever your system is updated via cPanel, Nginx gets updated too.

Additionally, having seen almost all other Nginx installers for cPanel, none of them get it right when it comes to caching. These configurations either do nothing (Nginx just proxies everything to Apache = no benefit at all) or they screw up websites with user-generated content (e.g. forums, e-shops etc.).

Why not ask your tech support to completely remove cpnginx (stop & remove Nginx, remove mod_rpaf module for Apache)?

Then you can run the installation on your own and see that it'll work.

**Comment by elaka** [comment]
Please note that rpaf.conf is under /etc/httpd/conf and not under /usr/local/apache/conf/includes/
will that cause issues?

**Comment by fevangelou** [comment]
If you have CentOS 6 it shouldn't be there unless you use a different build
for Apache than the one that cPanel provides.

**Comment by highacid** [comment]
```
Resolving Dependencies
--> Running transaction check
---> Package nginx.x86_64 1:1.8.1-1.el7.ngx will be installed
--> Processing Conflict: ea-apache24-2.4.18-1.1.x86_64 conflicts webserver
--> Finished Dependency Resolution
Error: ea-apache24 conflicts with 1:nginx-1.8.1-1.el7.ngx.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by fevangelou** [comment]
@highacid https://github.com/nuevvo/engintron#requirements Read this please
