### ISSUE TITLE
Reloading and Restart Nginx doesnt work!

### ISSUE THREAD

**Issue by frilogg** [nuevvo/engintron#59]
Just have a nrew Centos 7.2 installation with a clean installation of WHM54 Build 2. Im using EasyApace 3. 

The installation went ok. When I use the control panel under plugins on go to status it seems that everythings working but when I try Reload or Restart - I get - 

Something went wrong, check the Nginx log.
Restarting from Command line (putty) works perfect.

**Comment by fevangelou** [comment]
Released v1.5.1 a little while ago.

Can you install on top please?

If this doesn't work, I'm assuming it has to do with the way CentOS 7 is aliasing "service X action" for both Apache and Nginx.

As I state in the "Requirements" section, CentOS 7 is not yet fully tested. We aim to fix this by the coming Monday.

**Comment by frilogg** [comment]
Hi, thank you for the quick feedback, I will test it out now. As this is a new server I would love figuring this out.

**Comment by frilogg** [comment]
Still get this "Something went wrong, check the Nginx log."  - so where is this log? So I can post the feedback here.

**Comment by fevangelou** [comment]
Check the options in Engintron's WHM app, can't miss it.

**Comment by frilogg** [comment]
Showing last 100 entries from /var/log/nginx/error.log

2016/02/06 17:16:45 [error] 6746#0: *12 connect() failed (111: Connection refused) while connecting to upstream, client: 84.214.148.90, server: localhost, request: "GET / HTTP/1.1", upstream: "http://136.243.176.89:8080/", host: "serv5.domenetorget.net"
2016/02/06 17:17:33 [error] 6746#0: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 84.214.148.90, server: localhost, request: "GET / HTTP/1.1", upstream: "http://136.243.176.89:8080/", host: "serv5.domenetorget.net"
2016/02/06 17:17:46 [error] 6746#0: *15 connect() failed (111: Connection refused) while connecting to upstream, client: 84.214.148.90, server: localhost, request: "GET /whm HTTP/1.1", upstream: "http://136.243.176.89:8080/whm", host: "serv5.domenetorget.net"
2016/02/06 17:19:23 [alert] 6746#0: *18 open socket #18 left in connection 2
2016/02/06 17:19:23 [alert] 6746#0: *19 open socket #21 left in connection 5
2016/02/06 17:19:23 [alert] 6746#0: aborting
2016/02/06 17:21:55 [crit] 1219#0: opendir() "/tmp/engintron_dynamic" failed (2: No such file or directory)
2016/02/06 17:21:55 [crit] 1219#0: opendir() "/tmp/engintron_static" failed (2: No such file or directory)
2016/02/06 17:23:20 [error] 1211#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 84.214.148.90, server: localhost, request: "GET /whm HTTP/1.1", upstream: "http://136.243.176.89:8080/whm", host: "serv5.domenetorget.net"
2016/02/06 17:23:26 [error] 1211#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 84.214.148.90, server: localhost, request: "GET / HTTP/1.1", upstream: "http://136.243.176.89:8080/", host: "serv5.domenetorget.net"
2016/02/06 18:55:21 [error] 27088#0: *8 connect() failed (111: Connection refused) while connecting to upstream, client: 84.214.148.90, server: localhost, request: "GET / HTTP/1.1", upstream: "http://136.243.176.89:8080/", host: "serv5.domenetorget.net"

**Comment by fevangelou** [comment]
Engintron v1.5.2 is now available to download with full CentOS 7 support and updating via WHM. Enjoy :)
